spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017
      database: transaction
management:
  endpoints:
    web:
      exposure:
        include: health, beans

transaction:
  validation:
    enabled: true
    banco: true
    horario: true

    #  host: localhost
     # port: 27017
      #username: admin
      #password: admin
     # database: transaction